version: '3.9'

services:
  db_postgres318:
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - '5432:5432'
    volumes:
      - './db_data:/var/lib/postgresql/data'
